---
- name: Enable baseurl in repositories (mirror mode)
  command: sed -i 's/^#baseurl/baseurl/' {{ item }}
  when: mode == "mirror" and ansible_distribution == "CentOS"
  with_items:
   - /etc/yum.repos.d/CentOS-Base.repo
  tags:
      - common
      - repositories

- name: Disable mirrorlist in repositories (mirror mode)
  command: sed -i 's/^mirrorlist/#mirrorlist/g' {{ item }}
  when: mode == "mirror" and ansible_distribution == "CentOS"
  with_items:
   - /etc/yum.repos.d/CentOS-Base.repo
  tags:
      - common
      - repositories

- name: Spoof CentOS Base hostname in /etc/hosts (mirror mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*mirror\.centos\.org$'
              line="{{ packages_mirror_ip }}    mirror.centos.org"
  when: mode == "mirror"
  notify:
   - Clean yum repositories
  tags:
      - common
      - repositories

- name: Disable baseurl in repositories (internet mode)
  command: sed -i 's/^baseurl/#baseurl/g' {{ item }}
  when: mode == "internet" and ansible_distribution == "CentOS"
  with_items:
   - /etc/yum.repos.d/CentOS-Base.repo
  tags:
      - common
      - repositories

- name: Enable mirrorlist in repositories (internet mode)
  command: sed -i 's/^#mirrorlist/mirrorlist/g' {{ item }}
  when: mode == "internet" and ansible_distribution == "CentOS"
  with_items:
   - /etc/yum.repos.d/CentOS-Base.repo
  tags:
      - common
      - repositories

- name: Remove any CentOS Base hostname spoofing (internet mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*mirror\.centos\.org$'
              state=absent
  when: mode == "internet" and ansible_distribution == "CentOS"
  notify:
   - Clean yum repositories
  tags:
      - common
      - repositories

